#cloud-config
write_files:
  - path: /opt/rancher/bin/install.yml
    permissions: "0700"
    content: |
      #cloud-config
      hostname: rancher-os
      ssh_authorized_keys:
        - "-- YOUR SSH KEY here --"
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      echo Y | sudo ros install -f -c /opt/rancher/bin/install.yml -d /dev/sda
      